stages:
  - configure
  - build
  - install
  - test

minimal_configure:
  stage: configure
  before_script:
    -  ./autogen.sh
  script: CC=~/external_software/gcc/5.3.0/bin/gcc ./configure --prefix=$PWD/gpi2-install-dir --with-ethernet
  tags:
    - centos-6.5
  cache:
    untracked: true

minimal_build:
  stage: build
  script: make
  tags:
    - centos-6.5
  cache:
    untracked: true

minimal_install:
  stage: install
  script: make install
  tags:
    - centos-6.5
  cache:
    untracked: true

minimal_test:
  stage: test
  script:
    - hostname -f > tests/machines
    - hostname -f >> tests/machines
    - make check
  tags:
    - centos-6.5
  cache:
    untracked: true
